#!/usr/bin/env bash
#installs nginx server and sets default content to Holberton Shool
ssh ubuntu@142.44.167.26 'sudo apt-get update && sudo apt-get -y install nginx'
ssh ubuntu@142.44.167.26 'echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html'

