#!/usr/bin/env bash
#starts nginx as nginx user
sed -i 's/listen 80 /listen 8080 /' /etc/nginx/sites-available/default
sed -i 's/:80 /:8080 /' /etc/nginx/sites-available/default
sed -i 's/listen 80 /listen 8080 /' /etc/nginx/sites-enabled/default
sed -i 's/:80 /:8080 /' /etc/nginx/sites-enabled/default
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
pkill apache2
chmod -R 755 /etc/nginx/
sudo -u nginx service nginx restart
