#!/bin/bash
#display info about subdomains
if [ "$#" -eq 0 ]; then
	echo "Usage: ./1-worl_wide_web <domain> <subdomain>"
	exit 0
fi

shellcheck disable=SC2086

dig_it(){
	s=$(dig "$1.$2" | grep -A1 'ANSWER SECTION:')
	echo "The subdomain $1 is a $(echo "$s" | awk 'FNR == 2 {print$4}') and points to $(echo "$s" | awk 'FNR == 2 {print$5}')"
}


if [ "$2" ]; then
   	dig_it "$2" "$1"
else
	dig_it www "$1"
	dig_it lb-01 "$1"
	dig_it web-01 "$1"
	dig_it web-02 "$1"
fi
