#!/usr/bin/env bash
# install nginx, add custom header
shellcheck disable=SC2154
sudo apt update && sudo apt -y install nginx
sudo service nginx start
sudo sed -i "21i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
