#!/usr/bin/env bash
#displays information about holberton file
FILE="holbertonschool"
if [ -e $FILE ]; then
   echo "$FILE file exists"
else
   echo "$FILE file does not exist"
fi

if [ -f $FILE ]; then
   echo "$FILE file is a regular file"
fi
if [ -s $FILE ]; then
   echo "$FILE file is not empty"
else
   echo "$FILE file is empty"
fi
