#!/usr/bin/env bash
#2fix listening to port 80
sed -i 's/listen 8080 default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
sed -i /ipv6only=on/d' /etc/nginx/sites-enabled/default
service nginx restart
service nginx stop
