#!/usr/bin/env bash
#starts nginx as nginx user
sed -i -e 's/listen 80 /listen 8080 /' -e 's/:80 /:8080 /' /etc/nginx/sites-available/default
sed -i -e 's/listen 80 /listen 8080 /' -e 's/:80 /:8080 /' /etc/nginx/sites-enabled/default
pkill apache2
chmod -R 755 /etc/nginx/
sudo -u nginx service nginx restart
